### ISSUE TITLE
HCL2 example of "windows_container": true uses ubuntu image

### ISSUE THREAD

**Issue by mloskot** [hashicorp/packer-plugin-docker#153]
On https://developer.hashicorp.com/packer/plugins/builders/docker#docker-for-windows
this example does not use correct, does it?

![image](https://github.com/hashicorp/packer-plugin-docker/assets/80741/3d4b5b92-52c2-46eb-bcae-dfa37120aa65)

**Comment by lbajolet-hashicorp** [comment]
Good catch @mloskot!

I'll open a PR to fix this, thanks for the report

**Comment by mloskot** [comment]
Thank you @lbajolet-hashicorp
